### ISSUE TITLE
Entrypoint path is not correct when running docker in docker

### ISSUE THREAD

**Issue by dragosMC91** [unfor19/install-aws-cli-action#24]
I might be misunderstanding this but I have to following situation: 

I am running docker in docker.
When the container is started, the following mapping is being done: `/runner/_work/_actions/` (host) -> `/__w/_actions` (work container)
When I try to install the aws cli via this action I then get
```
sudo: /runner/_work/_actions/unfor19/install-aws-cli-action/v1.0.3/entrypoint.sh: command not found
Error: Process completed with exit code 1.
```

My question is, why is the script executed from the `GITHUB_ACTION_PATH` folder (https://github.com/unfor19/install-aws-cli-action/blob/master/action.yml#L49) and not from `ROOTDIR` ? 

Thanks in advance!

(I tried to override `GITHUB_ACTION_PATH` but it looks like gh doesn't allow this)

**Comment by unfor19** [comment]
Hi @dragosMC91 , the variable [GITHUB_ACTION_PATH](https://docs.github.com/en/actions/learn-github-actions/variables) replaced `github.action_path`, see https://github.com/unfor19/install-aws-cli-action/pull/23

I'm unsure how to replicate your actions, but as an alternative, you can add a step in your pipeline, as mentioned in the [README.md](https://github.com/unfor19/install-aws-cli-action#other-options), so instead of using this action as a classic action, in your complex use-case of docker-in-docker, you might be able to use-

```yml
steps:
# Your steps ...
      - name: Install AWS CLI
        shell: bash
        run: |
           curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
           sudo chmod +x install-aws.sh && \
           sudo ./install-aws.sh "v2" "amd64" && \
           sudo rm install-aws.sh
```

Is that good enough?
