### ISSUE TITLE
Not working with prebuilt Playwright docker images

### ISSUE THREAD

**Issue by MattyBalaam** [unfor19/install-aws-cli-action#35]
Trying to use this with prebuilt docker container causes as error while installing with default settings. Perhaps there are some settings that need to be passed down, or maybe the action needs to be updated?

```
jobs:
  run:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.1

…

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.7

```

Result

<img width="748" alt="Image" src="https://github.com/user-attachments/assets/82cc88a8-1ba1-4113-93a0-fc8fba9a60cd" />

```
Run unfor19/install-aws-cli-action@v1
Run echo "AWS_CLI_VERSION=2" >> $GITHUB_ENV
Run sudo --preserve-env ${GITHUB_ACTION_PATH}/entrypoint.sh
/__w/_temp/7693fbc9-c0be-462a-8eea-e95ff131e1a8.sh: line 1: sudo: command not found
Error: Process completed with exit code 127.
```
